name: CI

on:
  workflow_call:
    inputs:
      lang:
        description: Lenguaje del proyecto (node | python).
        required: true
        type: string

jobs:
  node:
    if: ${{ inputs.lang == 'node' }}
    uses: CuevaTech/cuevatech-infra-workflows/.github/workflows/ci-node.yml@main

  python:
    if: ${{ inputs.lang == 'python' }}
    uses: CuevaTech/cuevatech-infra-workflows/.github/workflows/ci-python.yml@main
